services:
  db:
    image: postgres:15
    container_name: lony-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: lony_db
      POSTGRES_USER: lony_user
      POSTGRES_PASSWORD: lony_pass
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: lony-backend-web
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
